### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by bloha** [rajce-client/request-pool#1]
# v1 Roadmap
## Sessions
- [ ] Create a control session for a group of requests
- [ ] Add an ability to abort a session
- [ ] Add an ability to pause a session
- [ ] Add an ability to resume a session
- [ ] Add an ability to create a child session

## Priority queue
- [ ] Use a priority queue for all sessions
- [ ] Add an ability to set a priority for a session
- [ ] Add an ability to set a priority for a request
- [ ] Use the highest priority for resumed sessions

## Error resistance
- [ ] Use an exponential backoff strategy
- [ ] Wrap a request with a timeout
